import { useState } from 'react';
import { motion } from 'framer-motion';
import { Download } from 'lucide-react';
import type { ShipMateReport } from '../types';
import { OverviewTab } from '../tabs/OverviewTab';
import { PlanTab } from '../tabs/PlanTab';
import { RepoTab } from '../tabs/RepoTab';
import { SecurityTab } from '../tabs/SecurityTab';
import { TestsTab } from '../tabs/TestsTab';
import { ReleaseTab } from '../tabs/ReleaseTab';

const TABS = [
  { id: 'overview',  label: '🏠 Overview' },
  { id: 'repo',      label: '🔍 Repo' },
  { id: 'plan',      label: '📋 Plan' },
  { id: 'security',  label: '🔒 Security' },
  { id: 'tests',     label: '🧪 Tests' },
  { id: 'release',   label: '🚢 Release' },
] as const;

type TabId = typeof TABS[number]['id'];

export function ReportTabs({ report }: { report: ShipMateReport }) {
  const [active, setActive] = useState<TabId>('overview');

  function download() {
    const lines = [
      `# ShipMate AI — Readiness Report`,
      `**Repo:** ${report.repo.full_name}  **Branch:** ${report.repo.branch}`,
      `**Score:** ${report.readiness_score}/100  **Recommendation:** ${report.ship_recommendation}`,
      ``,
      `## Key Blockers`,
      ...report.key_blockers.map(b => `- ${b}`),
      ``,
      `## Next Actions`,
      ...report.next_actions.map(a => `- ${a}`),
      ``,
      `## Score Breakdown`,
      `| Dimension | Score |`,
      `|-----------|-------|`,
      `| Repo Structure (20%) | ${report.score_breakdown.repo_score} |`,
      `| Delivery Plan (25%) | ${report.score_breakdown.delivery_score} |`,
      `| Security (30%) | ${report.score_breakdown.security_score} |`,
      `| Test Coverage (25%) | ${report.score_breakdown.test_score} |`,
      ``,
      `_Generated by ShipMate AI at ${report.generated_at}_`,
    ].join('\n');
    const url = URL.createObjectURL(new Blob([lines], { type: 'text/markdown' }));
    const a = document.createElement('a');
    a.href = url; a.download = 'shipmate-report.md'; a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="rounded-2xl border bg-slate-800/60 border-slate-700/40 overflow-hidden">
      {/* Tab bar */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-slate-700/40 gap-2 flex-wrap">
        <div className="flex gap-1 flex-wrap">
          {TABS.map(tab => (
            <button
              key={tab.id}
              onClick={() => setActive(tab.id)}
              className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${
                active === tab.id
                  ? 'bg-blue-600/20 text-blue-300 ring-1 ring-blue-500/40'
                  : 'text-slate-400 hover:text-slate-200 hover:bg-slate-700/40'
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>
        <button
          onClick={download}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-medium
                     bg-emerald-500/10 text-emerald-400 border border-emerald-500/20
                     hover:bg-emerald-500/20 transition-colors"
        >
          <Download size={13} /> Export
        </button>
      </div>

      {/* Tab content */}
      <div className="p-5">
        <motion.div
          key={active}
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.2 }}
        >
          {active === 'overview'  && <OverviewTab report={report} />}
          {active === 'repo'      && <RepoTab data={report.agents.repo_lens} />}
          {active === 'plan'      && <PlanTab data={report.agents.plan_forge} />}
          {active === 'security'  && <SecurityTab data={report.agents.guardrail} />}
          {active === 'tests'     && <TestsTab data={report.agents.testpilot} />}
          {active === 'release'   && <ReleaseTab report={report} />}
        </motion.div>
      </div>
    </div>
  );
}
