"""
CoderOrchestrator — turns an `ActuateRequest` into a real GitHub PR.

Pipeline:
  1. Resolve which file paths Coder should see (heuristic — see _resolve_target_paths).
  2. Fetch their current contents from GitHub (parallel; new files come back empty).
  3. Build a CoderBrief and run CoderAgent (Bedrock, structured output).
  4. Create a fresh branch off the base branch.
  5. Commit each file Coder produced (create or update).
  6. Open a PR against the base branch.
  7. Return ActuateResponse with the PR URL.

Stateless. The caller (the /api/actuate route) gets ALL the context from
the FindingPayload + RepoLensSummary the client passed inline.

If `open_pr=False`, we still create the branch and commit but skip the PR
step — useful for testing without GitHub PR noise.
"""

from __future__ import annotations

import asyncio
import logging
import os
import re
from datetime import datetime, timezone
from typing import Dict, List, Optional, Tuple

from app.agents.coder_agent import CoderAgent, CoderBrief, CoderOutput
from app.schemas.api_schemas import (
    ActuateRequest, ActuateResponse, ActuatedFile, FindingPayload, RepoLensSummary,
)
from app.services import ast_lint
from app.services import inflight_registry as ir
from app.services import validation_gate as vg
from app.services.github_api_service import GitHubAPIService
from app.services.github_pr_service import GitHubPRService

logger = logging.getLogger("shipmate.coder_orchestrator")

# Whether the pytest gate runs inside the actuate flow. The gate writes to
# the LOCAL working tree (snapshot+restore) — only meaningful when the
# backend runs from a checkout of the repo being actuated (the dogfood
# case). For arbitrary external repos there's nothing local to test against,
# so the gate is a no-op there. Controlled by env so CI / hosted deploys
# can disable it.
_PYTEST_GATE_ENABLED = os.getenv("SHIPMATE_PYTEST_GATE", "1") == "1"

# The repo this backend checkout corresponds to. The pytest gate only fires
# when the actuate target matches — otherwise we'd be running ShipMate's own
# tests against a patch meant for someone else's repo.
_SELF_REPO = os.getenv("SHIPMATE_SELF_REPO", "WalkingDevFlag/Shipmate-AI")

# How aggressive the smart vs fast model routing is.
# Security and CI/CD changes warrant Sonnet; tests/docs are fine on Haiku.
_SMART_KINDS = {"guardrail", "next_action"}
_SMART_CATEGORIES = {"secrets", "auth", "cors", "injection", "config", "ci_cd"}


def _slugify(text: str, max_len: int = 32) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "-", text.lower()).strip("-")
    return s[:max_len] or "actuate"


def _finding_signature(finding: FindingPayload) -> str:
    """Stable cross-context identifier. MUST match coder_loop._finding_signature
    so the CLI loop and the UI orchestrator agree on which finding is which
    (shared finding_journal + inflight claims). Format: kind::title::file."""
    title = (finding.title or "").strip().lower()[:80]
    file_hint = (finding.file or "").lower()
    return f"{finding.kind}::{title}::{file_hint}"


def _branch_name(finding: FindingPayload) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    return f"shipmate/{finding.kind}-{_slugify(finding.id)}-{ts}"


def _commit_message(finding: FindingPayload, path: str) -> str:
    head = finding.title[:60].rstrip()
    return f"shipmate({finding.kind}): {head} — {path}"


def _pr_title(finding: FindingPayload) -> str:
    icon = {
        "guardrail": "🛡️",
        "milestone": "🚀",
        "blocker": "🚧",
        "test": "🧪",
        "next_action": "✨",
    }.get(finding.kind, "🤖")
    return f"{icon} ShipMate: {finding.title[:80]}"


def _pr_body(req: ActuateRequest, coder: CoderOutput) -> str:
    f = req.finding
    lines: List[str] = [
        f"## ShipMate AI — automated patch",
        "",
        f"**Originating finding:** `{f.kind}` / `{f.id}`"
        + (f" · severity **{f.severity}**" if f.severity else ""),
        f"**Title:** {f.title}",
        "",
        "### Description",
        f.description or "_(none)_",
        "",
    ]
    if f.recommendation:
        lines += ["### ShipMate recommendation", f.recommendation, ""]
    lines += ["### Coder summary", coder.summary or "_(no summary returned)_", ""]
    if coder.files:
        lines += ["### Files changed"]
        for cf in coder.files:
            lines.append(f"- `{cf.path}` — {cf.rationale}")
        lines.append("")
    if coder.skipped:
        lines += ["### Skipped (no change needed)"]
        for p in coder.skipped:
            lines.append(f"- `{p}`")
        lines.append("")
    lines += [
        "---",
        "_This PR was generated by ShipMate AI's Coder agent. Please review carefully before merging._",
        f"_Run id: {datetime.now(timezone.utc).isoformat()} · base: `{req.branch}`_",
    ]
    return "\n".join(lines)


# ── Target-path heuristics ───────────────────────────────────────────────────

_BACKEND_HINT_NAMES = ("main.py", "app.py", "server.py", "index.ts", "index.js", "main.ts")


def _resolve_target_paths(
    finding: FindingPayload,
    context: Optional[RepoLensSummary],
    file_tree: List[str],
) -> List[str]:
    """
    Pick up to 5 paths to show Coder. Empty strings are filtered. New (non-existent)
    paths are allowed — the orchestrator treats them as "create file".
    """
    paths: List[str] = []
    tree_set = set(file_tree)
    entry_points = list(context.entry_points) if context else []

    # 1. Explicit hint from the finding (GuardRail/file or test target).
    if finding.file:
        paths.append(finding.file)

    cat = (finding.category or "").lower()
    kind = finding.kind

    # 2. Category-based mapping.
    if kind == "guardrail":
        if cat in {"secrets", "cors", "auth", "injection", "config"}:
            for p in entry_points[:2]:
                if p and p not in paths:
                    paths.append(p)
            for p in file_tree:
                name = p.rsplit("/", 1)[-1]
                if name in _BACKEND_HINT_NAMES and p not in paths:
                    paths.append(p)
                    if len(paths) >= 4:
                        break
            if cat == "secrets" and ".gitignore" in tree_set and ".gitignore" not in paths:
                paths.append(".gitignore")
        elif cat == "deps":
            for p in ("requirements.txt", "package.json", "pyproject.toml"):
                if p in tree_set and p not in paths:
                    paths.append(p)

    elif kind in {"milestone", "blocker", "next_action"}:
        if cat == "ci_cd":
            ci_path = ".github/workflows/ci.yml"
            paths.append(ci_path)
        elif cat == "testing":
            entry = entry_points[0] if entry_points else ""
            stem = entry.rsplit("/", 1)[-1].rsplit(".", 1)[0] if entry else "main"
            paths.append(f"tests/test_{stem or 'main'}.py")
            if entry and entry not in paths:
                paths.append(entry)
        elif cat in {"feature", "infra", "docs", "security"}:
            for p in entry_points[:2]:
                if p and p not in paths:
                    paths.append(p)

    elif kind == "test":
        # finding.file may already carry SuggestedTest.target_file (the
        # production code under test). If so, KEEP it — Coder needs to see
        # the real implementation to ground assertions. Then add a sibling
        # test file to write into. Also include EXISTING test files for the
        # same module — Coder must see them so it doesn't rewrite tests
        # that are already passing (existing coverage rule #3).
        prod_file = finding.file if finding.file in tree_set else None
        if prod_file:
            stem = prod_file.rsplit("/", 1)[-1].rsplit(".", 1)[0]
            # Find any existing test files that target this module.
            existing = [
                f for f in file_tree
                if (f"test_{stem}" in f.rsplit("/", 1)[-1] or f"{stem}.test." in f.rsplit("/", 1)[-1])
                and ("/tests/" in f or "/__tests__/" in f or "tests/" in f)
            ][:2]
            for ex in existing:
                if ex not in paths:
                    paths.append(ex)
            # Add a target test path (creates new file if not in existing).
            if prod_file.startswith("backend/"):
                target_test = f"backend/tests/test_{stem}.py"
            elif prod_file.startswith("frontend/"):
                ext = prod_file.rsplit(".", 1)[1] if "." in prod_file else "ts"
                target_test = f"frontend/src/__tests__/{stem}.test.{ext}"
            else:
                target_test = f"backend/tests/test_{stem}.py"
            if target_test not in paths and target_test not in existing:
                paths.append(target_test)
        else:
            stem = _slugify(finding.id, max_len=40) or "case"
            paths.append(f"backend/tests/test_{stem}.py")
            # Also include the entry point so Coder has SOMETHING real to import.
            for p in entry_points[:1]:
                if p and p not in paths:
                    paths.append(p)

    # 3. Fallback to top entry point.
    if not paths and entry_points:
        paths.append(entry_points[0])

    # 4. Last-ditch fallback: README so Coder can at least leave a note.
    if not paths:
        paths.append("README.md")

    # Dedupe + soft cap. The cap is on the INPUT context size (how many
    # files we fetch from GitHub and feed Coder), not the output. We keep
    # this generous (15) so Coder has enough context for cross-file
    # changes; it's still bounded so the prompt doesn't blow up token
    # budget on huge target_files blobs. Each file is also independently
    # truncated at 30k chars by the Coder agent's _truncate_for_prompt.
    _CONTEXT_PATH_LIMIT = 15
    seen = set()
    deduped: List[str] = []
    for p in paths:
        if p and p not in seen:
            seen.add(p)
            deduped.append(p)
        if len(deduped) >= _CONTEXT_PATH_LIMIT:
            break
    return deduped


async def _fetch_current_contents(
    token: str, owner: str, repo: str, paths: List[str],
    ref: Optional[str] = None,
) -> Dict[str, str]:
    """
    Best-effort parallel fetch. Missing files → empty string (Coder treats those
    as new-file creations). `ref` should be the analysis target branch — without
    it, GitHub serves the repo's default branch which is almost never what we
    want when analyzing a feature branch.
    """
    sem = asyncio.Semaphore(5)

    async def fetch(path: str) -> Tuple[str, str]:
        async with sem:
            try:
                content = await GitHubAPIService.get_file_content(
                    token, owner, repo, path, ref=ref,
                )
                return path, (content or "")
            except Exception as e:
                logger.warning("Could not fetch %s: %s — treating as new file", path, e)
                return path, ""

    pairs = await asyncio.gather(*[fetch(p) for p in paths])
    return {p: c for p, c in pairs}


def _deployment_hint(finding: FindingPayload) -> str:
    cat = (finding.category or "").lower()
    if finding.kind in _SMART_KINDS or cat in _SMART_CATEGORIES:
        return "smart"
    return "fast"


# ── Post-Coder safety lint ──────────────────────────────────────────────────

_NEW_TEST_THEATER_PATTERNS = (
    re.compile(r"status_code\s+in\s*[\(\[][^)\]]*4\d\d", re.MULTILINE),
    re.compile(r"^\s*assert\s+True\s*$", re.MULTILINE),
)


def _looks_like_test_path(path: str) -> bool:
    name = path.rsplit("/", 1)[-1]
    return (
        name.startswith("test_")
        or name.endswith((".test.tsx", ".test.ts", ".spec.ts", ".spec.tsx"))
        or "/tests/" in path
        or "/__tests__/" in path
    )


def _lint_coder_output(
    coder_out: CoderOutput,
    target_files: Dict[str, str],
    file_tree: List[str],
) -> List[str]:
    """
    Returns a list of structural issues (empty list = pass). The orchestrator
    rejects the patch (no branch/PR) if this returns anything non-empty.

    Import / symbol checks are delegated to `ast_lint` (real AST parsing) —
    that module replaced the brittle regex detectors that false-positived on
    aliased / TYPE_CHECKING / try-ImportError imports. Test-theater and
    .gitkeep-theater checks stay here (they're cheap regex on text and don't
    benefit from AST).
    """
    issues: List[str] = []
    for cf in coder_out.files:
        original = target_files.get(cf.path, "")

        if cf.path.endswith(".py"):
            # Fatal: unparseable Python. No point shipping a file that won't import.
            syntax_err = ast_lint.syntax_error_of(cf.new_content, cf.path)
            if syntax_err:
                issues.append(syntax_err)
                continue  # skip further checks — they'd just re-report the parse failure

            bad = ast_lint.detect_bad_imports(cf.new_content, original, file_tree)
            if bad:
                issues.append(
                    f"{cf.path}: hallucinated first-party imports not in repo or "
                    f"original file: {bad}"
                )
            stale_named = ast_lint.detect_stale_named_imports(
                cf.new_content, target_files, coder_out.files,
            )
            if stale_named:
                issues.append(
                    f"{cf.path}: imports symbols that don't exist in the "
                    f"target module(s): {stale_named[:5]}"
                )

        # NEW test theater = patterns Coder added that weren't in the original.
        if _looks_like_test_path(cf.path):
            for pat in _NEW_TEST_THEATER_PATTERNS:
                if pat.search(cf.new_content) and not pat.search(original):
                    issues.append(
                        f"{cf.path}: introduces test theater pattern "
                        f"`{pat.pattern[:50]}` (assertions accepting 4xx as success "
                        f"or `assert True`)"
                    )

        # Only flag .gitkeep inside dirs the codebase normally ignores —
        # bootstrapping an empty `nginx/certs/` or `data/` is legitimate.
        if re.search(
            r"(__pycache__|/build|/dist|/\.venv|/node_modules)/[^/]*\.gitkeep$",
            cf.path,
        ):
            issues.append(
                f"{cf.path}: .gitkeep inside an ignored/build directory "
                "(theater pattern — preserves a dir the patch claims to remove)"
            )
    return issues


def _build_task(finding: FindingPayload) -> str:
    """The instruction string that becomes the Coder agent's `task`."""
    pieces = [f"[{finding.kind.upper()}] {finding.title}"]
    if finding.description:
        pieces.append(f"Description: {finding.description}")
    if finding.recommendation:
        pieces.append(f"Recommended approach: {finding.recommendation}")
    pieces.append(
        "Apply the minimal, focused patch needed to address this. "
        "Don't refactor surrounding code or introduce unrelated changes."
    )
    return "\n\n".join(pieces)


# ── Top-level orchestrator ───────────────────────────────────────────────────

class CoderOrchestrator:

    @classmethod
    async def run_actuation(cls, req: ActuateRequest) -> ActuateResponse:
        ctx = req.context or RepoLensSummary()
        branch_name = _branch_name(req.finding)

        # 1. Get the file tree once so target resolution can probe it.
        try:
            file_tree = await GitHubAPIService.get_file_tree(
                req.access_token, req.owner, req.repo, req.branch,
            )
        except Exception as e:
            logger.warning("file_tree fetch failed: %s — proceeding without it", e)
            file_tree = []

        target_paths = _resolve_target_paths(req.finding, ctx, file_tree)
        logger.info("Resolved %d target paths for %s/%s: %s",
                    len(target_paths), req.finding.kind, req.finding.id, target_paths)

        # 2. Fetch current contents — pinned to the same `req.branch` we
        # resolved file_tree against. Without this, GitHub serves the
        # default branch and Coder is given a stale picture, leading to
        # patches that re-introduce imports/symbols already removed.
        target_files = await _fetch_current_contents(
            req.access_token, req.owner, req.repo, target_paths,
            ref=req.branch,
        )

        # 3. Run Coder (sync, on a worker thread).
        brief = CoderBrief(
            task=_build_task(req.finding),
            repo_full_name=f"{req.owner}/{req.repo}",
            primary_language=ctx.primary_language,
            tech_stack=ctx.tech_stack,
            entry_points=ctx.entry_points,
            target_files=target_files,
            finding_kind=req.finding.kind,
            finding_id=req.finding.id,
            finding_severity=req.finding.severity,
        )
        agent = CoderAgent()
        coder_out: CoderOutput = await asyncio.to_thread(
            agent.run, brief, _deployment_hint(req.finding),
        )

        if not coder_out.files:
            # Coder decided no change is needed (or skipped everything).
            return ActuateResponse(
                status="no_change",
                pr_url=None,
                branch_name=branch_name,
                files_changed=[],
                skipped=coder_out.skipped or target_paths,
                summary=coder_out.summary or "Coder determined no patch was needed.",
            )

        # 3b. Quality lint — reject hallucinations BEFORE branching/committing.
        # This is the second line of defense after the system prompt — if Coder
        # invents imports despite rule #1, we catch it here and return a clean
        # error instead of opening a bogus PR.
        lint_issues = _lint_coder_output(coder_out, target_files, file_tree)
        if lint_issues:
            logger.warning(
                "Coder output rejected by post-lint for %s/%s: %s",
                req.finding.kind, req.finding.id, lint_issues,
            )
            return ActuateResponse(
                status="lint_rejected",
                pr_url=None,
                branch_name=branch_name,
                files_changed=[],
                skipped=[cf.path for cf in coder_out.files],
                summary=(
                    f"Coder produced output but post-lint rejected it: "
                    f"{'; '.join(lint_issues)}. The patch was discarded "
                    f"and no branch/PR was created. Original Coder summary: "
                    f"{coder_out.summary[:300]}"
                ),
            )

        # 3c. Path claim — atomic cross-process lock so a UI click and the
        # CLI loop (or two UI clicks) can't both rewrite the same file. If
        # any path is already claimed, bail with `path_busy` immediately
        # (user-facing retry — see ActuateButton). Always released in `finally`.
        repo_full = f"{req.owner}/{req.repo}"
        claimed_paths: List[str] = []
        claimer = f"actuate:{req.finding.kind}:{req.finding.id}"
        sig = _finding_signature(req.finding)
        try:
            for cf in coder_out.files:
                if not ir.claim_path(repo_full, req.branch, cf.path, sig, claimer):
                    holder = ir.get_path_claim(repo_full, req.branch, cf.path)
                    held_by = (holder or {}).get("claimed_by", "another actuate")
                    logger.info("path_busy: %s held by %s", cf.path, held_by)
                    return ActuateResponse(
                        status="path_busy",
                        pr_url=None,
                        branch_name=branch_name,
                        files_changed=[],
                        skipped=[cf.path for cf in coder_out.files],
                        summary=(
                            f"Another actuate is currently editing `{cf.path}` "
                            f"(held by {held_by}). Retry once it finishes."
                        ),
                    )
                claimed_paths.append(cf.path)

            # 3d. Local pytest gate — only when actuating THIS repo on a local
            # checkout (the dogfood case). For external repos there's no local
            # tree to test against, so we skip. Snapshot → apply → smoke import
            # → pytest → restore-on-regression. If the patch drops the pass
            # count, reject with `pytest_rejected` and DON'T open a PR.
            gate_ran = False
            if _PYTEST_GATE_ENABLED and repo_full == _SELF_REPO:
                gate_ran = True
                serialized = [
                    {"path": cf.path, "new_content": cf.new_content}
                    for cf in coder_out.files
                ]
                result, snap = await asyncio.to_thread(vg.gate_patch, serialized)
                if not result.passed:
                    await asyncio.to_thread(vg.restore_snapshot, snap)
                    logger.warning(
                        "pytest gate rejected %s/%s: %s",
                        req.finding.kind, req.finding.id, result.reason,
                    )
                    return ActuateResponse(
                        status="pytest_rejected",
                        pr_url=None,
                        branch_name=branch_name,
                        files_changed=[],
                        skipped=[cf.path for cf in coder_out.files],
                        summary=(
                            f"Patch passed lint but failed the local pytest gate: "
                            f"{result.reason}. The working tree was restored and no "
                            f"PR was created. Coder summary: {coder_out.summary[:200]}"
                        ),
                    )
                # Gate passed — restore the tree (GitHub commit is the source of
                # truth; we don't want the local checkout to drift). Bump the
                # baseline so a later actuate can't pass by re-clearing these.
                await asyncio.to_thread(vg.restore_snapshot, snap)
                vg.update_baseline(result.after)
                logger.info(
                    "pytest gate passed for %s/%s (%dp → %dp)",
                    req.finding.kind, req.finding.id, result.before, result.after,
                )

            # 4. Create the branch.
            base_sha = await GitHubPRService.get_branch_sha(
                req.access_token, req.owner, req.repo, req.branch,
            )
            await GitHubPRService.create_branch(
                req.access_token, req.owner, req.repo, branch_name, base_sha,
            )

            # 5. Commit each file (sequential — Contents API needs fresh sha per write).
            committed: List[ActuatedFile] = []
            for cf in coder_out.files:
                existing_sha = await GitHubPRService.get_file_sha(
                    req.access_token, req.owner, req.repo, cf.path, branch_name,
                )
                try:
                    await GitHubPRService.put_file(
                        req.access_token,
                        req.owner,
                        req.repo,
                        cf.path,
                        cf.new_content,
                        _commit_message(req.finding, cf.path),
                        branch_name,
                        sha=existing_sha,
                    )
                except Exception as e:
                    # GitHub returns 404 (not 403!) when the OAuth token lacks the
                    # `workflow` scope and the file lives under .github/workflows/.
                    # Surface a clean, actionable error instead of a bare 404.
                    if cf.path.startswith(".github/workflows/") and "404" in str(e):
                        raise RuntimeError(
                            f"Cannot write {cf.path}: your GitHub OAuth token is missing "
                            "the `workflow` scope. Sign out and reconnect GitHub from the "
                            "sidebar to re-grant scopes, then retry."
                        ) from e
                    raise
                committed.append(ActuatedFile(path=cf.path, rationale=cf.rationale))

            # 6. Open PR (optional).
            pr_url: Optional[str] = None
            pr_number: Optional[int] = None
            if req.open_pr:
                pr_url, pr_number = await GitHubPRService.create_pull_request(
                    req.access_token,
                    req.owner,
                    req.repo,
                    _pr_title(req.finding),
                    _pr_body(req, coder_out),
                    head=branch_name,
                    base=req.branch,
                )

                # 7. Register the PR with CIWatcher so we can self-heal CI failures.
                #    Lazy import keeps the orchestrator import-light and avoids
                #    a cycle (ci_watcher imports coder_agent).
                try:
                    from app.services.ci_watcher import CIWatcher
                    CIWatcher.register(
                        owner=req.owner,
                        repo=req.repo,
                        pr_number=pr_number,
                        pr_url=pr_url,
                        branch=branch_name,
                        base_branch=req.branch,
                        access_token=req.access_token,
                        finding=req.finding,
                        repo_lens=ctx,
                    )
                except Exception as e:
                    # Watcher registration is best-effort — don't fail the actuate
                    # call if the watcher couldn't start.
                    logger.warning("CIWatcher.register failed: %s — PR opened without auto-fix", e)

                # Journal: this finding now has an open PR in flight.
                try:
                    ir.journal_set_state(
                        sig, repo_full, "in_progress",
                        pr_url=pr_url, bump_attempt=True,
                    )
                except Exception as e:
                    logger.debug("journal_set_state failed (non-fatal): %s", e)

            return ActuateResponse(
                status="complete",
                pr_url=pr_url,
                branch_name=branch_name,
                files_changed=committed,
                skipped=coder_out.skipped,
                summary=coder_out.summary,
            )
        finally:
            # Always release path claims — whether we succeeded, returned a
            # rejection mid-try, or raised. A leaked claim would block the
            # path until its 10-min TTL lapses.
            for p in claimed_paths:
                try:
                    ir.release_path(repo_full, req.branch, p, claimer)
                except Exception as e:
                    logger.debug("release_path failed for %s: %s", p, e)
