"""
CoderOrchestrator — turns an `ActuateRequest` into a real GitHub PR.

Pipeline:
  1. Resolve which file paths Coder should see (heuristic — see _resolve_target_paths).
  2. Fetch their current contents from GitHub (parallel; new files come back empty).
  3. Build a CoderBrief and run CoderAgent (Bedrock, structured output).
  4. Create a fresh branch off the base branch.
  5. Commit each file Coder produced (create or update).
  6. Open a PR against the base branch.
  7. Return ActuateResponse with the PR URL.

Stateless. The caller (the /api/actuate route) gets ALL the context from
the FindingPayload + RepoLensSummary the client passed inline.

If `open_pr=False`, we still create the branch and commit but skip the PR
step — useful for testing without GitHub PR noise.
"""

from __future__ import annotations

import asyncio
import logging
import re
from datetime import datetime, timezone
from typing import Dict, List, Optional, Tuple

from app.agents.coder_agent import CoderAgent, CoderBrief, CoderOutput
from app.schemas.api_schemas import (
    ActuateRequest, ActuateResponse, ActuatedFile, FindingPayload, RepoLensSummary,
)
from app.services.github_api_service import GitHubAPIService
from app.services.github_pr_service import GitHubPRService

logger = logging.getLogger("shipmate.coder_orchestrator")

# How aggressive the smart vs fast model routing is.
# Security and CI/CD changes warrant Sonnet; tests/docs are fine on Haiku.
_SMART_KINDS = {"guardrail", "next_action"}
_SMART_CATEGORIES = {"secrets", "auth", "cors", "injection", "config", "ci_cd"}


def _slugify(text: str, max_len: int = 32) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "-", text.lower()).strip("-")
    return s[:max_len] or "actuate"


def _branch_name(finding: FindingPayload) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    return f"shipmate/{finding.kind}-{_slugify(finding.id)}-{ts}"


def _commit_message(finding: FindingPayload, path: str) -> str:
    head = finding.title[:60].rstrip()
    return f"shipmate({finding.kind}): {head} — {path}"


def _pr_title(finding: FindingPayload) -> str:
    icon = {
        "guardrail": "🛡️",
        "milestone": "🚀",
        "blocker": "🚧",
        "test": "🧪",
        "next_action": "✨",
    }.get(finding.kind, "🤖")
    return f"{icon} ShipMate: {finding.title[:80]}"


def _pr_body(req: ActuateRequest, coder: CoderOutput) -> str:
    f = req.finding
    lines: List[str] = [
        f"## ShipMate AI — automated patch",
        "",
        f"**Originating finding:** `{f.kind}` / `{f.id}`"
        + (f" · severity **{f.severity}**" if f.severity else ""),
        f"**Title:** {f.title}",
        "",
        "### Description",
        f.description or "_(none)_",
        "",
    ]
    if f.recommendation:
        lines += ["### ShipMate recommendation", f.recommendation, ""]
    lines += ["### Coder summary", coder.summary or "_(no summary returned)_", ""]
    if coder.files:
        lines += ["### Files changed"]
        for cf in coder.files:
            lines.append(f"- `{cf.path}` — {cf.rationale}")
        lines.append("")
    if coder.skipped:
        lines += ["### Skipped (no change needed)"]
        for p in coder.skipped:
            lines.append(f"- `{p}`")
        lines.append("")
    lines += [
        "---",
        "_This PR was generated by ShipMate AI's Coder agent. Please review carefully before merging._",
        f"_Run id: {datetime.now(timezone.utc).isoformat()} · base: `{req.branch}`_",
    ]
    return "\n".join(lines)


# ── Target-path heuristics ───────────────────────────────────────────────────

_BACKEND_HINT_NAMES = ("main.py", "app.py", "server.py", "index.ts", "index.js", "main.ts")


def _resolve_target_paths(
    finding: FindingPayload,
    context: Optional[RepoLensSummary],
    file_tree: List[str],
) -> List[str]:
    """
    Pick up to 5 paths to show Coder. Empty strings are filtered. New (non-existent)
    paths are allowed — the orchestrator treats them as "create file".
    """
    paths: List[str] = []
    tree_set = set(file_tree)
    entry_points = list(context.entry_points) if context else []

    # 1. Explicit hint from the finding (GuardRail/file or test target).
    if finding.file:
        paths.append(finding.file)

    cat = (finding.category or "").lower()
    kind = finding.kind

    # 2. Category-based mapping.
    if kind == "guardrail":
        if cat in {"secrets", "cors", "auth", "injection", "config"}:
            for p in entry_points[:2]:
                if p and p not in paths:
                    paths.append(p)
            for p in file_tree:
                name = p.rsplit("/", 1)[-1]
                if name in _BACKEND_HINT_NAMES and p not in paths:
                    paths.append(p)
                    if len(paths) >= 4:
                        break
            if cat == "secrets" and ".gitignore" in tree_set and ".gitignore" not in paths:
                paths.append(".gitignore")
        elif cat == "deps":
            for p in ("requirements.txt", "package.json", "pyproject.toml"):
                if p in tree_set and p not in paths:
                    paths.append(p)

    elif kind in {"milestone", "blocker", "next_action"}:
        if cat == "ci_cd":
            ci_path = ".github/workflows/ci.yml"
            paths.append(ci_path)
        elif cat == "testing":
            entry = entry_points[0] if entry_points else ""
            stem = entry.rsplit("/", 1)[-1].rsplit(".", 1)[0] if entry else "main"
            paths.append(f"tests/test_{stem or 'main'}.py")
            if entry and entry not in paths:
                paths.append(entry)
        elif cat in {"feature", "infra", "docs", "security"}:
            for p in entry_points[:2]:
                if p and p not in paths:
                    paths.append(p)

    elif kind == "test":
        # finding.file may carry SuggestedTest.target_file; if not set, synthesize.
        if not paths:
            stem = _slugify(finding.id, max_len=40) or "case"
            paths.append(f"tests/test_{stem}.py")

    # 3. Fallback to top entry point.
    if not paths and entry_points:
        paths.append(entry_points[0])

    # 4. Last-ditch fallback: README so Coder can at least leave a note.
    if not paths:
        paths.append("README.md")

    # Dedupe + cap.
    seen = set()
    deduped: List[str] = []
    for p in paths:
        if p and p not in seen:
            seen.add(p)
            deduped.append(p)
        if len(deduped) >= 5:
            break
    return deduped


async def _fetch_current_contents(
    token: str, owner: str, repo: str, paths: List[str],
) -> Dict[str, str]:
    """
    Best-effort parallel fetch. Missing files → empty string (Coder treats those
    as new-file creations).
    """
    sem = asyncio.Semaphore(5)

    async def fetch(path: str) -> Tuple[str, str]:
        async with sem:
            try:
                content = await GitHubAPIService.get_file_content(token, owner, repo, path)
                return path, (content or "")
            except Exception as e:
                logger.warning("Could not fetch %s: %s — treating as new file", path, e)
                return path, ""

    pairs = await asyncio.gather(*[fetch(p) for p in paths])
    return {p: c for p, c in pairs}


def _deployment_hint(finding: FindingPayload) -> str:
    cat = (finding.category or "").lower()
    if finding.kind in _SMART_KINDS or cat in _SMART_CATEGORIES:
        return "smart"
    return "fast"


def _build_task(finding: FindingPayload) -> str:
    """The instruction string that becomes the Coder agent's `task`."""
    pieces = [f"[{finding.kind.upper()}] {finding.title}"]
    if finding.description:
        pieces.append(f"Description: {finding.description}")
    if finding.recommendation:
        pieces.append(f"Recommended approach: {finding.recommendation}")
    pieces.append(
        "Apply the minimal, focused patch needed to address this. "
        "Don't refactor surrounding code or introduce unrelated changes."
    )
    return "\n\n".join(pieces)


# ── Top-level orchestrator ───────────────────────────────────────────────────

class CoderOrchestrator:

    @classmethod
    async def run_actuation(cls, req: ActuateRequest) -> ActuateResponse:
        ctx = req.context or RepoLensSummary()
        branch_name = _branch_name(req.finding)

        # 1. Get the file tree once so target resolution can probe it.
        try:
            file_tree = await GitHubAPIService.get_file_tree(
                req.access_token, req.owner, req.repo, req.branch,
            )
        except Exception as e:
            logger.warning("file_tree fetch failed: %s — proceeding without it", e)
            file_tree = []

        target_paths = _resolve_target_paths(req.finding, ctx, file_tree)
        logger.info("Resolved %d target paths for %s/%s: %s",
                    len(target_paths), req.finding.kind, req.finding.id, target_paths)

        # 2. Fetch current contents.
        target_files = await _fetch_current_contents(
            req.access_token, req.owner, req.repo, target_paths,
        )

        # 3. Run Coder (sync, on a worker thread).
        brief = CoderBrief(
            task=_build_task(req.finding),
            repo_full_name=f"{req.owner}/{req.repo}",
            primary_language=ctx.primary_language,
            tech_stack=ctx.tech_stack,
            entry_points=ctx.entry_points,
            target_files=target_files,
            finding_kind=req.finding.kind,
            finding_id=req.finding.id,
            finding_severity=req.finding.severity,
        )
        agent = CoderAgent()
        coder_out: CoderOutput = await asyncio.to_thread(
            agent.run, brief, _deployment_hint(req.finding),
        )

        if not coder_out.files:
            # Coder decided no change is needed (or skipped everything).
            return ActuateResponse(
                status="no_change",
                pr_url=None,
                branch_name=branch_name,
                files_changed=[],
                skipped=coder_out.skipped or target_paths,
                summary=coder_out.summary or "Coder determined no patch was needed.",
            )

        # 4. Create the branch.
        base_sha = await GitHubPRService.get_branch_sha(
            req.access_token, req.owner, req.repo, req.branch,
        )
        await GitHubPRService.create_branch(
            req.access_token, req.owner, req.repo, branch_name, base_sha,
        )

        # 5. Commit each file (sequential — Contents API requires fresh sha per write).
        committed: List[ActuatedFile] = []
        for cf in coder_out.files:
            existing_sha = await GitHubPRService.get_file_sha(
                req.access_token, req.owner, req.repo, cf.path, branch_name,
            )
            try:
                await GitHubPRService.put_file(
                    req.access_token,
                    req.owner,
                    req.repo,
                    cf.path,
                    cf.new_content,
                    _commit_message(req.finding, cf.path),
                    branch_name,
                    sha=existing_sha,
                )
            except Exception as e:
                # GitHub returns 404 (not 403!) when the OAuth token lacks the
                # `workflow` scope and the file lives under .github/workflows/.
                # Surface a clean, actionable error instead of a bare 404.
                if cf.path.startswith(".github/workflows/") and "404" in str(e):
                    raise RuntimeError(
                        f"Cannot write {cf.path}: your GitHub OAuth token is missing "
                        "the `workflow` scope. Sign out and reconnect GitHub from the "
                        "sidebar to re-grant scopes, then retry."
                    ) from e
                raise
            committed.append(ActuatedFile(path=cf.path, rationale=cf.rationale))

        # 6. Open PR (optional).
        pr_url: Optional[str] = None
        pr_number: Optional[int] = None
        if req.open_pr:
            pr_url, pr_number = await GitHubPRService.create_pull_request(
                req.access_token,
                req.owner,
                req.repo,
                _pr_title(req.finding),
                _pr_body(req, coder_out),
                head=branch_name,
                base=req.branch,
            )

            # 7. Register the PR with CIWatcher so we can self-heal CI failures.
            #    Lazy import keeps the orchestrator import-light and avoids
            #    a cycle (ci_watcher imports coder_agent).
            try:
                from app.services.ci_watcher import CIWatcher
                CIWatcher.register(
                    owner=req.owner,
                    repo=req.repo,
                    pr_number=pr_number,
                    pr_url=pr_url,
                    branch=branch_name,
                    base_branch=req.branch,
                    access_token=req.access_token,
                    finding=req.finding,
                    repo_lens=ctx,
                )
            except Exception as e:
                # Watcher registration is best-effort — don't fail the actuate
                # call if the watcher couldn't start.
                logger.warning("CIWatcher.register failed: %s — PR opened without auto-fix", e)

        return ActuateResponse(
            status="complete",
            pr_url=pr_url,
            branch_name=branch_name,
            files_changed=committed,
            skipped=coder_out.skipped,
            summary=coder_out.summary,
        )
