"""
Posts a ShipMate analysis summary as a GitHub PR comment.

Called by the /api/analyze route when pr_number is present, and by the
webhook handler for automatically-triggered analyses.
"""
from __future__ import annotations

import logging
from typing import Optional

import httpx

from app.schemas.agent_schemas import ShipMateReport

logger = logging.getLogger("shipmate.github_comment")

_VERDICT_EMOJI = {
    "ready_to_ship": "✅",
    "mostly_ready":  "🟡",
    "needs_review":  "🟠",
    "risky_release": "🔴",
    "not_ready":     "🚫",
}

_SEV_EMOJI = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵", "info": "⚪"}

_COMMENT_MARKER = "<!-- shipmate-ai-report -->"


def _build_comment(report: ShipMateReport) -> str:
    rec = report.ship_recommendation
    emoji = _VERDICT_EMOJI.get(rec, "⚠️")
    verdict = rec.replace("_", " ").title()
    score = report.readiness_score
    bd = report.score_breakdown

    # Score breakdown table
    breakdown = (
        f"| Repo Health | Delivery | Security | Testing |\n"
        f"|:-----------:|:--------:|:--------:|:-------:|\n"
        f"| {bd.repo_score}/100 | {bd.delivery_score}/100 | {bd.security_score}/100 | {bd.test_score}/100 |"
    )

    # Top security findings (max 3)
    findings_section = ""
    findings = report.agents.guardrail.findings[:3] if report.agents.guardrail.findings else []
    if findings:
        rows = "\n".join(
            f"| {_SEV_EMOJI.get(f.severity.value if hasattr(f.severity, 'value') else str(f.severity), '⚪')} **{f.title}** | `{f.file or '—'}` |"
            for f in findings
        )
        findings_section = f"\n\n**Security Findings**\n| Finding | File |\n|---------|------|\n{rows}"

    # Key blockers (max 3)
    blockers_section = ""
    blockers = report.key_blockers[:3]
    if blockers:
        items = "\n".join(f"- {b}" for b in blockers)
        blockers_section = f"\n\n**Key Blockers**\n{items}"

    # Next actions (max 2)
    actions_section = ""
    actions = report.next_actions[:2]
    if actions:
        items = "\n".join(f"- {a}" for a in actions)
        actions_section = f"\n\n**Recommended Actions**\n{items}"

    return (
        f"{_COMMENT_MARKER}\n"
        f"## {emoji} ShipMate AI · Release Readiness Report\n\n"
        f"**Score: {score}/100** — {verdict}  \n"
        f"Branch: `{report.repo.branch}` · Repo: `{report.repo.full_name}`\n\n"
        f"{breakdown}"
        f"{findings_section}"
        f"{blockers_section}"
        f"{actions_section}\n\n"
        f"<sub>Generated by [ShipMate AI](https://github.com/WalkingDevFlag/Shipmate-AI) · "
        f"`{report.generated_at[:19].replace('T', ' ')} UTC`</sub>"
    )


async def post_pr_comment(
    token: str,
    owner: str,
    repo: str,
    pr_number: int,
    report: ShipMateReport,
) -> Optional[str]:
    """
    Post (or update) a ShipMate report comment on a GitHub PR.

    Returns the comment URL on success, None on failure (non-fatal).
    Idempotent: updates an existing ShipMate comment instead of creating
    a duplicate — identified by the hidden HTML marker.
    """
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    body = _build_comment(report)

    async with httpx.AsyncClient(timeout=15.0) as client:
        # 1. Find an existing ShipMate comment to update
        existing_id: Optional[int] = None
        try:
            resp = await client.get(
                f"https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/comments",
                headers=headers,
                params={"per_page": 50},
            )
            if resp.status_code == 200:
                for c in resp.json():
                    if _COMMENT_MARKER in (c.get("body") or ""):
                        existing_id = c["id"]
                        break
        except Exception as e:
            logger.warning("Could not list PR comments: %s", e)

        try:
            if existing_id:
                r = await client.patch(
                    f"https://api.github.com/repos/{owner}/{repo}/issues/comments/{existing_id}",
                    headers=headers,
                    json={"body": body},
                )
            else:
                r = await client.post(
                    f"https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/comments",
                    headers=headers,
                    json={"body": body},
                )
            r.raise_for_status()
            url: str = r.json().get("html_url", "")
            logger.info("PR comment posted: %s", url)
            return url
        except Exception as e:
            logger.warning("Failed to post PR comment on %s/%s#%d: %s", owner, repo, pr_number, e)
            return None
