from app.models.schemas import DeliveryManagerOutput, SprintTask
from typing import List


def run_delivery_manager_agent(feature_request: str, repo_context: str = "") -> DeliveryManagerOutput:
    """
    Delivery Manager Agent: Creates sprint plan, standup summary, and release readiness assessment.
    """

    sprint_plan: List[SprintTask] = [
        SprintTask(
            day="Sprint 1 — Week 1 (Days 1-3): Foundation",
            tasks=[
                "BE-001: Implement JWT auth middleware with refresh token rotation",
                "BE-002: Design and implement RBAC permission matrix",
                "DB-001: Create users, roles, permissions schema migration",
                "FE-001: Build Login page with form validation and error states",
            ],
            owner="Backend Team + Frontend Lead"
        ),
        SprintTask(
            day="Sprint 1 — Week 1 (Days 4-5): Integration",
            tasks=[
                "FE-002: Implement role-based route guards in React Router",
                "BE-004: Integrate OAuth2 Google/GitHub providers",
                "TEST-001: Write auth flow E2E test suite (Playwright)",
                "Security: Fix CVE-2022-23529 in jsonwebtoken dependency",
            ],
            owner="Full Stack + QA"
        ),
        SprintTask(
            day="Sprint 2 — Week 2 (Days 1-3): Analytics",
            tasks=[
                "BE-003: Build analytics aggregation service with Redis caching",
                "DB-002: Create analytics_events table with partitioning",
                "FE-003: Build analytics dashboard with charts and KPI cards",
                "API-003: Integration test analytics endpoints",
            ],
            owner="Backend Team + Frontend"
        ),
        SprintTask(
            day="Sprint 2 — Week 2 (Days 4-5): Polish & Release",
            tasks=[
                "FE-004: Admin user management panel",
                "Security: Implement rate limiting on auth endpoints",
                "DevOps: Configure CI/CD pipeline with security scanning",
                "QA: Full regression test run + performance benchmarks",
                "Docs: Update API documentation and deployment runbook",
            ],
            owner="Full Team"
        ),
    ]

    standup_summary = """**Daily Standup Summary — Generated by ShipMate AI**

🟢 **Completed Yesterday:**
- Auth middleware scaffolding committed to feature/auth-rbac branch
- Database schema reviewed and approved by DBA team
- JWT vulnerability CVE-2022-23529 patched in staging

🟡 **Working on Today:**
- RBAC permission matrix implementation (BE-002) — 60% complete
- Login page UI — blocked pending design token alignment
- OAuth2 Google integration — in progress

🔴 **Blockers:**
- Waiting on DevOps to provision Redis cluster in staging environment
- Design sign-off needed on role management UI before FE-004 can start
- Legal review pending for GDPR analytics consent implementation"""

    pr_review_summary = """**PR Review Summary — feature/auth-rbac → main**

📋 **PR #247: Add JWT Authentication & RBAC System**
Author: @dev-team | Reviewers: @tech-lead, @security-team

✅ **Approved:**
- JWT token generation logic is correct and uses RS256 algorithm
- Password hashing uses bcrypt with cost factor 12
- Database migrations are reversible and tested

⚠️ **Needs Revision:**
- Line 147: JWT secret fallback to hardcoded value if env var missing — REMOVE immediately
- Line 298: Missing input validation on role assignment endpoint
- Line 412: Console.log leaking user email in auth error handler

❌ **Blocking Issues:**
- No unit tests for token refresh edge cases
- Rate limiting middleware not applied to /api/auth/forgot-password
- Missing audit log entry for role changes"""

    cicd_recommendations = [
        "Add SAST scanning (Semgrep/Snyk) as required CI gate — block merge on critical findings",
        "Implement Dependabot/Renovate for automated dependency vulnerability PRs",
        "Add API contract testing with Pact to prevent breaking changes to auth endpoints",
        "Configure staging environment parity check — staging must match production config",
        "Add database migration dry-run step in CI before any merge to main",
        "Implement blue-green deployment strategy for zero-downtime auth service updates",
    ]

    next_actions = [
        "🔴 [P0] Fix JWT secret exposure — rotate secret in all environments TODAY",
        "🔴 [P0] Apply rate limiting to all auth endpoints before feature goes live",
        "🟠 [P1] Complete RBAC implementation and get security team sign-off",
        "🟠 [P1] Provision Redis cluster in staging for auth session store",
        "🟡 [P2] Schedule DBA review for analytics table partitioning strategy",
        "🟡 [P2] Get legal team to review GDPR compliance for analytics data",
        "🟢 [P3] Update team documentation with new auth architecture decisions",
    ]

    return DeliveryManagerOutput(
        sprint_plan=sprint_plan,
        standup_summary=standup_summary,
        pr_review_summary=pr_review_summary,
        cicd_recommendations=cicd_recommendations,
        release_readiness_score=72,
        next_actions=next_actions,
        estimated_release_date="2 weeks from sprint start (contingent on security sign-off)"
    )
